### ISSUE TITLE
Storage service error handling no space left

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#1881]
We should trigger the right exception to the client when there is not enough space on a `DiskStorage`:

```
2020-12-10 11:18:41 ERROR [%PARSER_ERROR[traceToken]] c.e.b.n.k.s.DiskStorageOperations - Unable to resolve location for path '/opt/binaries'
java.nio.file.FileSystemException: /opt/binaries/618ede2b-be5c-432d-a015-fe7e25f6e3df/b/6/3: No space left on device
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createDirectories(Unknown Source)
	at ch.epfl.bluebrain.nexus.kg.storage.DiskStorageOperations$SaveDiskFile.$anonfun$getLocation$1(DiskStorageOperations.scala:94)
```

**Comment by imsdu** [comment]
Nexus Storage will be decommissioned in 1.11
