### ISSUE TITLE
ClassCastException when saving errors on projections

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#2099]
When an error occurs while pushing documents to elasticsearch index we attempt to record the error but fail on serialization. It seems something related to the classLoader since it raises a `ClassCastException` but there is also the issue of the message being Boxed:

```
app 2021-02-26 18:55:02 ERROR c.e.b.n.d.s.p.s.StreamSupervisorBehavior - Stream b07328e7-4163-4563-8219-0b6738ff6463_1_3f605caa-97b7-49ee-acc3-57975c2b86cd events has failed.
app java.lang.ClassCastException: class ch.epfl.bluebrain.nexus.delta.plugins.elasticsearch.client.ElasticSearchBulk$Index cannot be cast to class scala.runtime.BoxedUnit (ch.epfl.bluebrain.nexus.delta.plugins.elasticsearch.client.ElasticSearchBulk$Index is in unnamed module of loader ch.epfl.bluebrain.nexus.delta.service.plugin.PluginClassLoader @4bb507af; scala.runtime.BoxedUnit is in unnamed module of loader 'app')
app 	at io.circe.Encoder$$anon$9.encodeObject(Encoder.scala:172)
app 	at io.circe.Encoder$AsObject.apply(Encoder.scala:826)
app 	at io.circe.Encoder$AsObject.apply$(Encoder.scala:826)
app 	at io.circe.Encoder$$anon$9.apply(Encoder.scala:172)
app 	at io.circe.syntax.package$EncoderOps$.asJson$extension(package.scala:10)
app 	at ch.epfl.bluebrain.nexus.delta.sourcing.projections.postgres.PostgresProjection.$anonfun$batchErrors$1(PostgresProjection.scala:111)
app 	at map @ ch.epfl.bluebrain.nexus.delta.kernel.utils.IOUtils.instant(IOUtils.scala:16)
app 	at map @ ch.epfl.bluebrain.nexus.delta.sourcing.projections.postgres.PostgresProjection.recordErrors(PostgresProjection.scala:147)
app 	at flatMap @ ch.epfl.bluebrain.nexus.delta.sourcing.projections.postgres.PostgresProjection.recordErrors(PostgresProjection.scala:147)
app 	at >> @ ch.epfl.bluebrain.nexus.delta.Main$.$anonfun$start$11(Main.scala:58)
app 	at >> @ ch.epfl.bluebrain.nexus.delta.Main$.$anonfun$start$11(Main.scala:58)
app 	at map @ fs2.internal.CompileScope.interruptibleEval(CompileScope.scala:418)
app 	at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:503)
app 	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
app 	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
app 	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
app 	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
app 	at map @ fs2.concurrent.Queue$InPartiallyApplied$$anon$4.$anonfun$dequeue1$3(Queue.scala:278)
```

**Comment by umbreak** [comment]
THis was fixed.
