### ISSUE TITLE
EvaluationTimeout or EvaluationError will blow up on the routes

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#2143]
Reproduce:
1. Set the elasticsearch view `base` in the config to a non existing Uri
2. Create a org
3. Create a project. You will see the following errors in the logs
```
app 2021-03-10 14:59:47 WARN  c.e.b.n.d.s.p.ShardedAggregate - A Task is hiding an error while 'processing EvaluationResult for the id 'myorg/myproject_https://bluebrain.github.io/nexus/vocabulary/defaultElasticSearchIndex''
app ch.epfl.bluebrain.nexus.delta.sourcing.processor.AggregateResponse$EvaluationTimeout: null
app 	at ch.epfl.bluebrain.nexus.delta.sourcing.processor.EventSourceProcessor.toAggregateResponse$1(EventSourceProcessor.scala:207)
app 	at ch.epfl.bluebrain.nexus.delta.sourcing.processor.EventSourceProcessor.$anonfun$behavior$14(EventSourceProcessor.scala:355)
app 	at ch.epfl.bluebrain.nexus.delta.sourcing.processor.EventSourceProcessor.$anonfun$behavior$3(EventSourceProcessor.scala:191)
```

The issue is related to the fact that when an `EvaluationError` occurs inside the `ShardedAggregate`we use `IO.terminate`, which doesn't allow us to catch errors. I think we shouldn't use IO.terminate, but have a specific `Rejection` for when `EvaluationError` happens, so that we can issue an `IO.raiseError(Rejection(mapper.to(evaluationError)))`

The culprit is around [here](https://github.com/BlueBrain/nexus/blob/master/delta/sourcing/src/main/scala/ch/epfl/bluebrain/nexus/delta/sourcing/processor/ShardedAggregate.scala#L123).

**Comment by umbreak** [comment]
It is due to [this line](https://github.com/BlueBrain/nexus/blob/master/delta/sourcing/src/main/scala/ch/epfl/bluebrain/nexus/delta/sourcing/processor/ShardedAggregate.scala#L123)
