### ISSUE TITLE
Certain tests fail to shutdown the ActorSystem properly

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#2148]
When exiting SBT after running service/plugin tests, sometimes the following kind of errors are shown:

```
2021-03-11 10:32:49 ERROR c.e.b.n.d.s.p.s.StreamSupervisorBehavior - Stream StorageIndex events has failed.
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "event_journal" not found; SQL statement:
select x2."ordering", x2."deleted", x2."persistence_id", x2."sequence_number", x2."writer", x2."write_timestamp", x2."adapter_manifest", x2."event_payload", x2."event_ser_id", x2."event_ser_manifest", x2."meta_payload", x2."meta_ser_id", x2."meta_ser_manifest" from "event_journal" x2, "event_tag" x3 where ((x3."tag" = ?) and ((x2."ordering" > ?) and (x2."ordering" <= ?))) and (x2."ordering" = x3."event_id") order by x2."ordering" limit ? [42102-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.command.Parser.readTableOrView(Parser.java:7628)
	at org.h2.command.Parser.readTableFilter(Parser.java:1970)
	at org.h2.command.Parser.parseSelectFromPart(Parser.java:2827)
	at org.h2.command.Parser.parseSelect(Parser.java:2959)
	at org.h2.command.Parser.parseQuerySub(Parser.java:2817)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:2649)
	at org.h2.command.Parser.parseQuery(Parser.java:2620)
	at org.h2.command.Parser.parsePrepared(Parser.java:868)
	at org.h2.command.Parser.parse(Parser.java:843)
	at org.h2.command.Parser.parse(Parser.java:815)
	at org.h2.command.Parser.prepareCommand(Parser.java:738)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:311)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at slick.jdbc.JdbcBackend$SessionDef.prepareStatement(JdbcBackend.scala:375)
	at slick.jdbc.JdbcBackend$SessionDef.prepareStatement$(JdbcBackend.scala:365)
	at slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:489)
	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:33)
	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
	at slick.jdbc.StreamingInvokerAction.emitStream(StreamingInvokerAction.scala:28)
	at slick.jdbc.StreamingInvokerAction.emitStream$(StreamingInvokerAction.scala:26)
	at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$2.emitStream(JdbcActionComponent.scala:214)
	at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$2.emitStream(JdbcActionComponent.scala:214)
	at slick.basic.BasicBackend$DatabaseDef$$anon$4.run(BasicBackend.scala:342)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at fromFuture @ streamz.converter.Converter.subscriberStream(Converter.scala:176)
	at runAsyncAndForget @ ch.epfl.bluebrain.nexus.delta.sourcing.projections.stream.StreamSupervisorBehavior$.start$1(StreamSupervisorBehavior.scala:76)
	at fromFuture @ streamz.converter.Converter.subscriberStream(Converter.scala:176)
	at map @ fs2.internal.CompileScope.interruptibleEval(CompileScope.scala:418)
	at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:503)
	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:463)
	at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:460)
	at flatMap @ fs2.internal.CompileScope.$anonfun$open$2(CompileScope.scala:146)
	at map @ fs2.internal.CompileScope.open(CompileScope.scala:137)
	at flatMap @ fs2.internal.CompileScope.open(CompileScope.scala:141)
	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$15(Algebra.scala:533)
	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$14(Algebra.scala:531)
	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
```

This may be related to test failures caused by initialization issues (when tests are aborted).

**Comment by adulbrich** [comment]
might be fixed, to monitor
